services:

  db:
    image: postgres:16
    container_name: odoo18_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo18_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8069"
      - "8072"
    volumes:
      - odoo_data:/opt/odoo/data
    environment:
      HOST: db
      PORT: 5432
      USER: odoo
      PASSWORD: odoo
    command:
      - --config=/etc/odoo/odoo.conf

volumes:
  odoo_db_data:
  odoo_data:
